### ISSUE TITLE
LOS 15.1 daily build

### ISSUE THREAD

**Issue by curbengh** [lineageos4microg/build_stats#2]
Now that the upstream LOS 15.1 is built [daily](https://www.xda-developers.com/lineageos-15-1-nightly-builds-monthly-14-1-builds/), but the latest L4M 15.1 build (I checked `angler`, `bullhead`, `cheeseburger`) is still at 5 Nov. Server can't handle the load or is it due to build error?

**Comment by Iey4iej3** [comment]
Lineage OS for MicroG seems to be still built weekly. And Xiaomi devices were taken down due to a DMCA issue, but now it is [coming back](https://www.xda-developers.com/lineageos-builds-back-online-xiaomi-devices/). Let's see whether Lineage OS for MicroG builts of Xiaomi will come back soon.
